# Generated by Django 4.1.3 on 2022-11-29 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='auctions.auctionlistings')),
                ('user_id', models.ManyToManyField(blank=True, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
